# Exported from Render on 2024-07-18T22:00:50Z
databases:
- name: db
  databaseName: bookis
  user: yo
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: bookis
  runtime: docker
  repo: https://github.com/alectrico-pro/bookis
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: db
      property: connectionString
  - key: HANAMI_ENV
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
